### ISSUE TITLE
With htmx

### ISSUE THREAD

**Issue by gedw99** [jhuddle/ponys#3]
Thank you for this framework .

it looks like it would be a clever system to use with htmx.

what you you think ? 

htmx is a SSR approach but Pony seems to not need compile or bundling and so it would allow the templating to run on the client

**Comment by jhuddle** [comment]
Hello @gedw99, my apologies for the late reply; thank you for getting in touch.

I had a brief look into htmx, as I'd not heard of it before - I suppose a lot of interoperability with Ponys would depend on whether/how/when the HTMLElement is monkey-patched by htmx in order to provide the kind of functionality it offers. If that is the case, the load order of the two libraries will be important, but I suspect it would be possible to make them play nicely together... perhaps you already found a way by now! :slightly_smiling_face:

**Comment by gedw99** [comment]
Hey @jhuddle 

thanks for the response. No I have not investigated how to use htmx with pony yet. 

I still think its a good match because of the server and client side possibilities that Pony has.

**Comment by dschissler** [comment]
[HTMX 2.0.0-alpha1](https://v2-0v2-0.htmx.org/posts/2024-01-26-htmx-2-0-0-alpha1-is-released/) has support for shadowdom.
